### PR TITLE
Add id to email for encryption and fix duplicate email issue

### LINKED ISSUE #91: Email service frontend- Duplicate email invites can be sent, which crashes frontend
Duplicate invites are sent, but subsequent one(s?) cant be removed after first one is removed

### PR DESCRIPTION
**Pull request by ryanchua00**
Add an inviteId to provide extra encryption for invite links

I updated the database schema to convert invite ids to cuid so we could use them to provide further encryption for invite links. Admin-signup page verifies the id matches that in the database before rendering the admin signup box.

Fix existing issue with email creation. Close #91 

Frontend now checks for existing emails before updating the list

### CODE REVIEW

File: backend/user-service/src/routes/invite.ts [hunk 1]
```diff
@@ -96,16 +96,29 @@ router.post("/", async (req: Request, res: Response) => {
...
+        mode: "cors",
+        credentials: "same-origin",
+        headers: {
+            "Content-Type": "application/json",
+        },
+        redirect: "follow",
+        referrerPolicy: "no-referrer",
+        body: JSON.stringify({
+            inviteeEmail: inviteeEmail,
+            inviteId: newInvitation.id.valueOf(),
```
Comment (ryanchua00) [inline backend/user-service/src/routes/invite.ts:110]: Fix #104

**Comment by bokuanT** [comment]
LGTM, will be putting another PR that merges this and #107

**Review by bokuanT — COMMENTED** [review]
Will be putting up another PR that merges this and another #107
